/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "binance",
            "endpoint": "https://3z7ss9d4ca.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:f7e0a278-5e8f-4846-b449-2e0824c29793",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EDbDNTTyq",
    "aws_user_pools_web_client_id": "3649mpcj8ic8edhcm6j4pl2ldb",
    "oauth": {}
};


export default awsmobile;
